# !tyml @cargo/Cargo
[package]
name = "tyml_source"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "TYML: type checker for markup language"
repository = "https://github.com/tyml-org/tyml/"

[dependencies]
extension-fn = "1.2.0"
