[workspace]
resolver = "2"
members = [
    "src/tyml",
    "src/tyml_diagnostic",
    "src/tyml_generator",
    "src/tyml_grammar",
    "src/tyml_parser",
    "src/tyml_source",
    "src/tyml_type",
    "src/tyml_validate",
]
