[Section]
comments = ["Hash"]

[Section.section]
kind = "Bracket"

[Section.section.literal.Custom]
regex = '[^ 　\t\[\]\n\r=;][^\[\]\n\r=;]*'

[Section.section.literal.Custom.option]
trim_space = true

[Section.section.literal.Custom.option.escape]
allow_escape = true
unicode = "Normal"

[Section.key_value]
kind = "Equal"

[Section.key_value.key.Custom]
regex = '[^ 　\t\[\]\n\r=;][^\[\]\n\r=;]*'

[Section.key_value.key.Custom.option]
trim_space = true

[Section.key_value.key.Custom.option.escape]
allow_escape = true
unicode = "Normal"

[Section.key_value.value.float]
allow_e = true
inf_nan_kind = "Insensitive"
allow_plus_minus = true
allow_under_line = true

[Section.key_value.value.any_string.Custom]
regex = '[^ 　\t\[\]\n\r=;][^\[\]\n\r=;]*'

[Section.key_value.value.any_string.Custom.option]
trim_space = true

[Section.key_value.value.any_string.Custom.option.escape]
allow_escape = true
unicode = "Normal"
