# !tyml message.tyml

[parse_error]
name = "%color:red{[SE%0] TYML構文エラー}"
[parse_error.0001]
message = "要素定義の記述形式が正しくありません"
label_0 = "不明なトークンです"
label_1 = "ここには%color:cyan{要素定義}もしくは%color:cyan{型定義}が必要です"
[parse_error.0002]
message = "文字'%color:red{%0}'は区切り文字として有効ではありません"
label_0 = "'%color:yellow{%0}'は不明な区切り文字です"
label_1 = "区切り文字として使用可能なのは、'%color:cyan{,}'と'%color:cyan{\\n}'(改行)のみです"
[parse_error.0003]
message = "要素定義の型を特定できません"
label_0 = "記述形式に誤りがあるため要素の型を識別できません"
label_1 = "%color:cyan{型}もしくは%color:cyan{既定値}を記述する必要があります"
[parse_error.0004]
message = "要素の型の記述形式が正しくありません"
label_0 = "不明なトークンです"
label_1 = "ここには%color:cyan{型名}もしくは%color:cyan{インライン型}が必要です"
[parse_error.0005]
message = "括弧'%color:yellow{{}'が閉じられていません"
label_0 = "'%color:cyan{\\}}'で閉じる必要があります"
[parse_error.0006]
message = "既定値の記述方法が正しくありません"
label_0 = "不明な値です"
[parse_error.0007]
message = "型の名称が指定されていません"
label_0 = "'%color:yellow{type}'の後には定義する型の%color:cyan{名称}が必要です"
[parse_error.0008]
message = "型の要素ブロックが記述されていません"
label_0 = "型名の後には'%color:cyan{{}'と'%color:cyan{\\}}'で囲われた要素ブロックが必要です"
[parse_error.0009]
message = "列挙型の名称が指定されていません"
label_0 = "'%color:yellow{enum}'の後には定義する型の%color:cyan{名称}が必要です"
[parse_error.0010]
message = "列挙型の要素ブロックが記述されていません"
label_0 = "型名の後には'%color:cyan{{}'と'%color:cyan{\\}}'で囲われた要素ブロックが必要です"
[parse_error.0011]
message = "列挙型の要素の記述形式が正しくありません"
label_0 = "これは列挙型の要素として有効ではありません"
note = "列挙型の要素は'%color:cyan{\"Element\"}'の形式です"
[parse_error.0012]
message = "列挙型の要素の区切り文字が正しくありません"
label_0 = "'%color:yellow{%0}'は不明な区切り文字です"
label_1 = "区切り文字として使用可能なのは、'%color:cyan{,}'と'%color:cyan{\\n}'(改行)のみです"
[parse_error.0013]
message = "ユニオン型の要素の記述形式が正しくありません"
label_0 = "ここにはユニオン型の型候補を記述すべきです"
[parse_error.0014]
message = "配列の基底型が指定されていません"
label_0 = "ここには配列の基底となる型が必要です"
label_1 = "配列は'%color:cyan{[int]}'のような形式で指定する必要があります"
[parse_error.0015]
message = "括弧'%color:yellow{[}'が閉じられていません"
label_0 = "'%color:cyan{]}'で閉じる必要があります"
[parse_error.0016]
message = "正規表現属性の記述形式が正しくありません"
label_0 = "'%color:yellow{@regex}'の後には文字列リテラルが必要です"
[parse_error.0017]
message = "数値属性の記述方法が正しくありません"
label_0 = "ここには'%color:cyan{..}'か'%color:cyan{..<}'か'%color:cyan{..=}'が必要です"
[parse_error.0018]
message = "数値属性の記述形式が正しくありません"
label_0 = "正しい形式ではありません"
note = "詳しくはドキュメントを参照してください"
[parse_error.0019]
message = "数値として有効ではありません"
label_0 = "数値としてのパースに失敗しました"
[parse_error.0020]
message = "大小関係が正しくありません"
label_0 = "左側の数値の方が大きいです"
[parse_error.0021]
message = "属性の'%color:yellow{or}'や'%color:yellow{and}'の記述方法が正しくありません"
label_0 = "属性を記述する必要があります"
[parse_error.0022]
message = "型属性が記述されていません"
label_0 = "'%color:cyan{(}'と'%color:cyan{)}'の間には型の属性を記述する必要があります"
[parse_error.0023]
message = "括弧'%color:yellow{(}'が閉じられていません"
label_0 = "'%color:cyan{)}'で閉じる必要があります"

[type_error]
name = "%color:red{[TE%0] 型エラー}"
[type_error.0001]
message = "不明な型が指定されています"
label_0 = "この名称'%color:red{%0}'の型が見つかりません"
[type_error.0002]
message = "既定値と型の互換性がありません"
label_0 = "この値は型'%color:yellow{%0}'として推論されます"
label_1 = "値はこの型'%color:yellow{%1}'と互換性がありません"
[type_error.0003]
message = "既定値が型の属性に適合しません"
label_0 = "この値は型の属性と一致しません"
label_1 = "値はこの型'%color:yellow{%0}'の属性と一致しません"
[type_error.0004]
message = "有効ではない属性が指定されています"
label_0 = "この属性は型'%color:yellow{%0}'の属性として有効ではありません"
note = "属性の種類と数値が有効かどうか再度確かめてみてください"
[type_error.0005]
message = "正規表現として有効ではない文字列が指定されています"
label_0 = "正規表現として有効ではありません"

[validate_error]
name = "%color:red{[VE%0] 検証エラー}"
[validate_error.0001]
message = "構造体以外の値が記述されています"
label_0 = "'%color:yellow{%0}'には構造体を指定する必要があります"
label_1 = "構造体として定義されているため、値や配列を指定できません"
[validate_error.0002]
message = "必要な値'%color:yellow{%0}'が見つかりません"
label_0 = "このセクションで'%color:yellow{%0}'の値を探しましたが見つかりませんでした"
label_1 = "ここで'%color:yellow{%0}'が定義されていますが、値は記述されていません"
note = "必要ない場合は型に'%color:cyan{?}'を付けることで、Optional型として扱うことができます"
[validate_error.0003]
message = "要素'%color:red{%0}'が重複しています"
label_0 = "この値は重複しています"
label_1 = "ここで既に記述されています"
[validate_error.0004]
message = "不明な要素'%color:red{%0}'が記述されています"
label_0 = "この要素は定義されていません"
[validate_error.0005]
message = "要素'%color:yellow{%0}'の値とその型'%color:yellow{%1}'が一致しません"
label_0 = "この値は定義されている型'%color:yellow{%1}'と一致しません"
label_1 = "要素'%color:yellow{%0}'は型'%color:yellow{%1}'として定義されています"
note = "型が一致しない子要素 : %color:yellow{%2}"
[validate_error.0006]
message = "要素'%color:yellow{%0}'に配列型'%color:yellow{%1}'ではない値が記述されています"
label_0 = "ここで記述されている値の型が定義されているものと一致しません"
label_1 = "要素'%color:yellow{%0}'は配列型'%color:yellow{%1}'として定義されています"

[ml_parse_error]
name = "%color:red{[GE%0] 構文エラー}"
[ml_parse_error.0001]
message = "全体としての記述形式が正しくありません"
label_0 = "不明なトークンです"
label_1 = "全体の記述形式である必要があります"
note = "通常、このエラーはJsonのように再帰的に構造を持つべき部分で発生します"
[ml_parse_error.0002]
message = "キーと値の記述形式が正しくありません"
label_0 = "不明なトークンです"
label_1 = "キーと値は'%color:cyan{%0}'の形式です"
[ml_parse_error.0003]
message = "セクションの記述形式が正しくありません"
label_0 = "不明なトークンです"
label_1 = "セクションは'%color:cyan{%0}'の形式です"
[ml_parse_error.0004]
message = "値の記述形式が正しくありません"
label_0 = "不明なトークンです"
label_1 = "ここには値を記述する必要があります"
[ml_parse_error.0005]
message = "改行されていません"
label_0 = "不明なトークンです"
label_1 = "ここで改行する必要があります"
[ml_parse_error.0006]
message = "コロン'%color:yellow{:}'が記述されていません"
label_0 = "コロンが必要です"
label_1 = "キーと値の間にコロン'%color:cyan{:}'を記述してみてください"
[ml_parse_error.0007]
message = "等号'%color:yellow{=}'が記述されていません"
label_0 = "等号が必要です"
label_1 = "キーと値の間に等号'%color:cyan{=}'を記述してみてください"
[ml_parse_error.0008]
message = "配列の記述形式が正しくありません"
label_0 = "不明なトークンです"
label_1 = "配列は'%color:cyan{%0}'の形式です"
[ml_parse_error.0009]
message = "インラインセクションの記述形式が正しくありません"
label_0 = "不明なトークンです"
label_1 = "この記述形式は有効ではありません"
[ml_parse_error.0010]
message = "括弧'%color:yellow{{}'が閉じられていません"
label_0 = "不明なトークンです"
label_1 = "括弧を'%color:cyan{\\}}'で閉じる必要があります"
[ml_parse_error.0011]
message = "余計な区切り文字が記述されています"
label_0 = "この区切り文字は必要ありません"
label_1 = "これを削除して見てください"

[lsp.message]
header_var_lookup_error = "指定された環境変数'%0'を解決できません"
failed_to_download_tyml = "指定されたTYMLファイルのダウンロードに失敗しました: %0"
tyml_file_error = "TYMLファイル'%0'を読み込めませんでした"
style_not_found = "言語定義'%0'が見つかりませんでした"
array_error_diagnostic = "配列の場合は他の要素のエラーが表示されることがあります"

[binary.message]
no_file_specified = "ファイルが指定されていません"
failed_to_read_file = "ファイルの読み込みに失敗しました"
no_header_found = "ヘッダが見つかりませんでした"
header_var_lookup_error = "ヘッダで指定された環境変数'%0'を解決できません"
failed_to_download_tyml = "ヘッダで指定されたTYMLファイルのダウンロードに失敗しました: %0"
header_no_style_found = "ヘッダで指定された言語定義'%0'が見つかりません"
header_no_tyml_found = "ヘッダで指定されたTYMLファイル'%0'が見つかりません"
header_tyml_is_not_file = "ヘッダで指定された'%0'はファイルではありません"
failed_to_read_tyml = "TYMLファイル'%0'の読み込みに失敗しました"
has_error = "ファイル'%0'にはエラーが含まれています"
