[parse_error]
name = "%color:red{[SE%0] 構文エラー}"
[parse_error.0001]
message = "要素定義の記述形式が正しくありません"
label_0 = "不明なトークンです"
label_1 = "ここには%color:cyan{要素定義}もしくは%color:cyan{型定義}が必要です"
[parse_error.0002]
message = "文字'%color:red{%0}'は区切り文字として有効ではありません"
label_0 = "'%color:yellow{%0}'は不明な区切り文字です"
label_1 = "区切り文字として使用可能なのは、'%color:cyan{,}'と'%color:cyan{\\n}'(改行)のみです"
[parse_error.0003]
message = "要素定義の型を特定できません"
label_0 = "記述形式に誤りがあるため要素の型を識別できません"
label_1 = "%color:cyan{型}もしくは%color:cyan{既定値}を記述する必要があります"
[parse_error.0004]
message = "要素の型の記述形式が正しくありません"
label_0 = "不明なトークンです"
label_1 = "ここには%color:cyan{型名}もしくは%color:cyan{インライン型}が必要です"
[parse_error.0005]
message = "括弧'%color:yellow{{}'が閉じられていません"
label_0 = "'%color:cyan{\\}}'で閉じる必要があります"
[parse_error.0006]
message = "既定値の記述方法が正しくありません"
label_0 = "不明な値です"
[parse_error.0007]
message = "型の名称が指定されていません"
label_0 = "'%color:yellow{type}'の後には定義する型の%color:cyan{名称}が必要です"
[parse_error.0008]
message = "型の要素ブロックが記述されていません"
label_0 = "型名の後には'%color:cyan{{}'と'%color:cyan{\\}}'で囲われた要素ブロックが必要です"
[parse_error.0009]
message = "列挙型の名称が指定されていません"
label_0 = "'%color:yellow{enum}'の後には定義する型の%color:cyan{名称}が必要です"
[parse_error.0010]
message = "列挙型の要素ブロックが記述されていません"
label_0 = "型名の後には'%color:cyan{{}'と'%color:cyan{\\}}'で囲われた要素ブロックが必要です"
[parse_error.0011]
message = "列挙型の要素の記述形式が正しくありません"
label_0 = "これは列挙型の要素として有効ではありません"
[parse_error.0012]
message = "列挙型の要素の区切り文字が正しくありません"
label_0 = "'%color:yellow{%0}'は不明な区切り文字です"
label_1 = "区切り文字として使用可能なのは、'%color:cyan{,}'と'%color:cyan{\\n}'(改行)のみです"
[parse_error.0013]
message = "ユニオン型の要素の記述形式が正しくありません"
label_0 = "ここにはユニオン型の型候補を記述すべきです"
[parse_error.0014]
message = "配列の基底型が指定されていません"
label_0 = "ここには配列の基底となる型が必要です"
label_1 = "配列は'%color:cyan{[int]}'のような形式で指定する必要があります"
[parse_error.0015]
message = "括弧'%color:yellow{[}'が閉じられていません"
label_0 = "'%color:cyan{]}'で閉じる必要があります"

[type_error]
name = "%color:red{[TE%0] 型エラー}"
[type_error.0001]
message = "不明な型が指定されています"
label_0 = "この名称'%color:red{%0}'の型が見つかりません"
[type_error.0002]
message = "既定値と型の互換性がありません"
label_0 = "この値は型'%color:yellow{%0}'として推論されます"
label_1 = "値はこの型'%color:yellow{%1}'と互換性がありません"
[type_error.0003]
message = "既定値が型の属性に適合しません"
label_0 = "この値は型の属性と一致しません"
label_1 = "値はこの型'%color:yellow{%0}'の属性と一致しません"

[validate_error]
name = "%color:red{[VE%0] 検証エラー}"
[validate_error.0001]
message = "構造体以外の値が記述されています"
label_0 = "'%color:yellow{%0}'には構造体を指定する必要があります"
label_1 = "構造体として定義されているため、値や配列を指定できません"
[validate_error.0002]
message = "必要な値が見つかりません"
label_0 = "ここを探しましたが見つかりませんでした"
label_1 = "ここで'%color:yellow{%0}'が定義されていますが、値は記述されていません"
note = "必要ない場合は型に'%color:cyan{?}'を付けることで、Optional型として扱うことができます"
[validate_error.0003]
message = "要素'%color:red{%0}'が重複しています"
label_0 = "この値は重複しています"
label_1 = "ここで既に記述されています"
[validate_error.0004]
message = "不明な要素'%color:red{%0}'が記述されています"
label_0 = "この要素は定義されていません"
[validate_error.0005]
message = "要素'%color:yellow{%0}'の値とその型'%color:yellow{%1}'が一致しません"
label_0 = "この値は定義されている型と一致しません"
label_1 = "要素'%color:yellow{%0}'は型'%color:yellow{%1}'として定義されています"
[validate_error.0006]
message = "要素'%color:yellow{%0}'に配列型'%color:yellow{%1}'ではない値が記述されています"
label_0 = "ここで記述されている値の型が定義されているものと一致しません"
label_1 = "要素'%color:yellow{%0}'は配列型'%color:yellow{%1}'として定義されています"
